# Generated by Django 4.2 on 2023-08-15 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Clientes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cliente", models.CharField(max_length=255, unique=True)),
                ("createdon", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CotizadorHistoricoFilters",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_desde", models.DateField(blank=True, null=True)),
                ("fecha_hasta", models.DateField(blank=True, null=True)),
                (
                    "articulo",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                ("tipo_2", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "tipo_cotiz",
                    models.CharField(blank=True, default=0, max_length=255, null=True),
                ),
                ("created_by", models.CharField(blank=True, max_length=255, null=True)),
                ("cliente", models.CharField(blank=True, max_length=255, null=True)),
                ("_id", models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="SopleteadoParametros",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_articulo",
                    models.CharField(blank=True, default="-", max_length=255),
                ),
                (
                    "consumo",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=5),
                ),
                (
                    "velocidad",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=5),
                ),
                ("createdon", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RecursosHumanos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("apellido", models.CharField(max_length=255, null=True)),
                ("nombre", models.CharField(max_length=255, null=True)),
                ("puesto", models.CharField(max_length=30, null=True)),
                (
                    "costo_hora_total",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "costo_mensual_total",
                    models.DecimalField(decimal_places=2, max_digits=20, null=True),
                ),
                ("createdon", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProduccionParametros",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gral_rotura_maquina",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=5),
                ),
                (
                    "gral_rotura_horno",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=5),
                ),
                (
                    "gral_malos_color_lavadero",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=5),
                ),
                ("gral_prod_mens_bsas", models.IntegerField(blank=True)),
                ("gral_prod_mens_mza", models.IntegerField(blank=True)),
                ("screen_cant_art", models.IntegerField(blank=True)),
                (
                    "screen_tpo_cambio",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=4),
                ),
                (
                    "screen_medida",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=10),
                ),
                ("screen_fab_hora", models.IntegerField(blank=True)),
                ("persmaq_maquinistas", models.IntegerField(blank=True)),
                ("persmaq_horno", models.IntegerField(blank=True)),
                (
                    "persmaq_autoelevador",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=3),
                ),
                ("persmaq_personal_asa", models.IntegerField(blank=True)),
                (
                    "persmaq_vel_calco",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=10),
                ),
                (
                    "horno_vel_tejido_1",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=10),
                ),
                (
                    "horno_vel_tejido_2",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=10),
                ),
                ("sopl_maquinistas", models.IntegerField(blank=True)),
                ("sopl_operarios", models.IntegerField(blank=True)),
                (
                    "sopl_tpo_setup",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=4),
                ),
                (
                    "sopl_perc_pint",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=5),
                ),
                (
                    "sopl_perc_solv",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=5),
                ),
                (
                    "sopl_perc_adit",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=5),
                ),
                (
                    "sopl_rotura",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=5),
                ),
                (
                    "sopl_lavadero",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=5),
                ),
                ("lav_limp_ser", models.IntegerField(blank=True)),
                ("lav_limp_sopl", models.IntegerField(blank=True)),
                ("ins_unid_film", models.IntegerField(blank=True)),
                ("ins_unid_cinta", models.IntegerField(blank=True)),
                ("dis_cant_bsas", models.IntegerField(blank=True)),
                ("dis_cant_mza", models.IntegerField(blank=True)),
                ("createdon", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FinanzasParametros",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "iibb_bsas",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=4),
                ),
                (
                    "iibb_mza",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=4),
                ),
                (
                    "hig_seg",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=4),
                ),
                (
                    "costo_deuda",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=4),
                ),
                (
                    "tasa_anual",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=6),
                ),
                (
                    "costo_funcionamiento",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=20),
                ),
                (
                    "perc_propio",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=4),
                ),
                (
                    "perc_cliente",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=4),
                ),
                (
                    "ventas_estimadas_propio",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=20),
                ),
                (
                    "ventas_estimadas_cliente",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=20),
                ),
                (
                    "compras_estimadas_propio",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=20),
                ),
                ("createdon", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CotizadorSerigrafia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "srg_quemado",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                (
                    "srg_hh_cambio_screen",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                (
                    "srg_hh_decoracion",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                (
                    "srg_hh_horno",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                (
                    "srg_mp_screen",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                (
                    "srg_hh_screen_cop",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                (
                    "srg_luz_gas",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                (
                    "srg_mp_pintura",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                (
                    "srg_sampista",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                (
                    "srg_rot_impresion",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                (
                    "srg_rot_horno",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                (
                    "srg_lavado",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                (
                    "srg_calco_vitrificable",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                (
                    "srg_mp_cinta_stretch",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                (
                    "srg_logistica",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                (
                    "srg_mantenimiento",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                (
                    "srg_calidad",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                (
                    "srg_setup",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                (
                    "srg_disenio_pelicula",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                (
                    "ctg_setup",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                (
                    "ctg_hh_sopleteadora",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                (
                    "ctg_luz_gas",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                (
                    "ctg_mp_pintura",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                (
                    "ctg_sampista",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                (
                    "ctg_rotura",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                (
                    "ctg_lavado",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                (
                    "ctg_mp_cinta_stretch",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                (
                    "ctg_mo_indirecta",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                (
                    "mp_articulo",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                (
                    "codigo_caja",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                (
                    "embalaje",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                (
                    "transporte",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                (
                    "costo_mp",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "costo_produccion",
                    models.DecimalField(decimal_places=2, max_digits=20),
                ),
                (
                    "costo_funcionamiento_articulo",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "costo_funcionamiento_decorado",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "costo_funcionamiento_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "costo_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "costo_unitario",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "costo_unitario_fab",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "costo_unitario_fab_articulo",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "costo_unitario_fab_decorado",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "costo_unitario_15",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "costo_unitario_30",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "costo_unitario_45",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "costo_unitario_60",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                ("createdon", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CosteoSerigrafia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("createdon", models.DateTimeField(auto_now_add=True)),
                (
                    "proyecto",
                    models.CharField(
                        blank=True, default=None, max_length=255, null=True
                    ),
                ),
                (
                    "tipo_2",
                    models.CharField(
                        blank=True, default="-", max_length=255, null=True
                    ),
                ),
                ("articulo", models.CharField(max_length=255)),
                ("art_propio", models.BooleanField()),
                ("cant_unidades", models.IntegerField()),
                ("maquina_auto", models.BooleanField(blank=True, null=True)),
                ("velocidad", models.IntegerField(blank=True, null=True)),
                ("cant_personal", models.IntegerField(blank=True, null=True)),
                ("horno", models.IntegerField(blank=True, null=True)),
                ("quemado", models.BooleanField(blank=True, null=True)),
                ("disenio", models.BooleanField(blank=True, null=True)),
                (
                    "disenio_perc",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "tipo_decorado",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("cant_colores", models.IntegerField(blank=True, null=True)),
                ("pintura_1", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "dibujo_1",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("relieve_1", models.CharField(blank=True, max_length=255, null=True)),
                ("pintura_2", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "dibujo_2",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("relieve_2", models.CharField(blank=True, max_length=255, null=True)),
                ("pintura_3", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "dibujo_3",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("relieve_3", models.CharField(blank=True, max_length=255, null=True)),
                ("pintura_4", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "dibujo_4",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("relieve_4", models.CharField(blank=True, max_length=255, null=True)),
                ("pintura_5", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "dibujo_5",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("relieve_5", models.CharField(blank=True, max_length=255, null=True)),
                ("pintura_6", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "dibujo_6",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("relieve_6", models.CharField(blank=True, max_length=255, null=True)),
                ("pintura_7", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "dibujo_7",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("relieve_7", models.CharField(blank=True, max_length=255, null=True)),
                ("pintura_8", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "dibujo_8",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("relieve_8", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "costo_calco",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("ctg_cant_colores", models.IntegerField(blank=True, null=True)),
                ("ctg_tipo", models.CharField(blank=True, max_length=255, null=True)),
                ("ctg_cant_pasadas", models.IntegerField(blank=True, null=True)),
                (
                    "ctg_color_1",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "ctg_cantidad_1",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "ctg_color_2",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "ctg_cantidad_2",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "ctg_color_3",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "ctg_cantidad_3",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "ctg_color_4",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "ctg_cantidad_4",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "ctg_color_5",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "ctg_cantidad_5",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "ctg_color_6",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "ctg_cantidad_6",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("codigo", models.CharField(blank=True, max_length=255, null=True)),
                ("embalaje", models.CharField(blank=True, max_length=255, null=True)),
                ("muestra", models.BooleanField(blank=True, null=True)),
                (
                    "transporte",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                (
                    "com_ventas",
                    models.DecimalField(
                        blank=True, decimal_places=2, default=0, max_digits=4, null=True
                    ),
                ),
                (
                    "com_otras",
                    models.DecimalField(
                        blank=True, decimal_places=2, default=0, max_digits=4, null=True
                    ),
                ),
                (
                    "iibb_bsas",
                    models.DecimalField(
                        blank=True, decimal_places=2, default=0, max_digits=4, null=True
                    ),
                ),
                (
                    "iibb_mza",
                    models.DecimalField(
                        blank=True, decimal_places=2, default=0, max_digits=4, null=True
                    ),
                ),
                (
                    "hig_seg",
                    models.DecimalField(
                        blank=True, decimal_places=2, default=0, max_digits=4, null=True
                    ),
                ),
                ("tipo_cotiz", models.CharField(default=0, max_length=255)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="modulos.clientes",
                    ),
                ),
                (
                    "cotizacion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="modulos.cotizadorserigrafia",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Articulos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("articulo", models.CharField(max_length=255, unique=True)),
                ("unidad", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "costo_ars_sinajuste",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                ("costo_ars", models.DecimalField(decimal_places=2, max_digits=20)),
                (
                    "costo_usd",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "costo_eur",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("tipo", models.CharField(max_length=255)),
                ("tipo_2", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "condicion_pago_dias",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "peso_kg",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "diametro_mm",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "asa",
                    models.CharField(
                        blank=True,
                        choices=[("SI", "SI"), ("NO", "NO")],
                        max_length=2,
                        null=True,
                    ),
                ),
                (
                    "consumo_g_cm2",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=10, null=True
                    ),
                ),
                (
                    "consumo_estandar",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=10, null=True
                    ),
                ),
                (
                    "velocidad_aplicacion_u_h",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("createdon", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
